In [2]:
#라이브러리 불러오기
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns

# 로컬 PC에서 csv 파일 로드
file_path = "C:/Users/LIM/OneDrive - gachon.ac.kr/바탕 화면/study/인공지능개론/quiz/car_evaluation.csv"  # 파일 경로 입력
data = pd.read_csv(file_path, header = None)  # 입력한 경로에 있는 파일 읽기
data.head()  # 올바른 데이터를 로드했는지 확인을 위해 상위 5행 출력

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [4]:
data.columns=['price', 'maint', 'doors', 'persons', 'lug_capacity', 'safety',
       'output']   #데이터에 컬럼 명이 없어 붙일 컬럼명 작성

In [6]:
data.columns  #컬럼명 출력

Index(['price', 'maint', 'doors', 'persons', 'lug_capacity', 'safety',
       'output'],
      dtype='object')

In [8]:
data  #컬럼명이 적용된 데이터 출력

price  maint  doors persons lug_capacity safety output
0     vhigh  vhigh      2       2        small    low  unacc
1     vhigh  vhigh      2       2        small    med  unacc
2     vhigh  vhigh      2       2        small   high  unacc
3     vhigh  vhigh      2       2          med    low  unacc
4     vhigh  vhigh      2       2          med    med  unacc
...     ...    ...    ...     ...          ...    ...    ...
1723    low    low  5more    more          med    med   good
1724    low    low  5more    more          med   high  vgood
1725    low    low  5more    more          big    low  unacc
1726    low    low  5more    more          big    med   good
1727    low    low  5more    more          big   high  vgood

[1728 rows x 7 columns]

In [10]:
data.isnull().sum()  #결측치 확인

price           0
maint           0
doors           0
persons         0
lug_capacity    0
safety          0
output          0
dtype: int64

In [12]:
columns = ['price', 'maint', 'doors', 'persons', 'lug_capacity', 'safety','output']  #엔코딩할 컬럼명 입력

In [14]:
label_encoders = {}   #엔코딩하기
for column in columns:
    label_encoders[column] = LabelEncoder()
    data[column] = label_encoders[column].fit_transform(data[column])

In [16]:
data  #엔코딩된 데이터 확인

price  maint  doors  persons  lug_capacity  safety  output
0         3      3      0        0             2       1       2
1         3      3      0        0             2       2       2
2         3      3      0        0             2       0       2
3         3      3      0        0             1       1       2
4         3      3      0        0             1       2       2
...     ...    ...    ...      ...           ...     ...     ...
1723      1      1      3        2             1       2       1
1724      1      1      3        2             1       0       3
1725      1      1      3        2             0       1       2
1726      1      1      3        2             0       2       1
1727      1      1      3        2             0       0       3

[1728 rows x 7 columns]

In [18]:
data['output'].value_counts()  #output column 엔코딩 결과 분류 카운트

output
2    1210
0     384
1      69
3      65
Name: count, dtype: int64

In [20]:
X = data.drop('output', axis=1).values  #입력값 분리
y = data['output'].values  #출력값 분리

In [22]:
X  #분리된 입력값 출력

array([[3, 3, 0, 0, 2, 1],
       [3, 3, 0, 0, 2, 2],
       [3, 3, 0, 0, 2, 0],
       ...,
       [1, 1, 3, 2, 0, 1],
       [1, 1, 3, 2, 0, 2],
       [1, 1, 3, 2, 0, 0]])

In [24]:
y  #분리된 출력값 출력

array([2, 2, 2, ..., 2, 1, 3])

In [26]:
scaler = StandardScaler()  #정규화를 위한 객체 생성
X = scaler.fit_transform(X)  #정규화

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)  #데이터 분할

In [30]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape  #데이터 분할 확인

((1382, 6), (346, 6), (1382,), (346,))

In [32]:
#라이브러리 불러오기
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

In [34]:
# Decision Tree
model = DecisionTreeClassifier(random_state=42)  # DecisionTreeClassifier 모델 생성 
model.fit(X_train, y_train)  # X_train 데이터의 패턴으로 모델을 학습
y_pred = model.predict(X_test)  # 학습된 모델로 X_test에 대해 예측

print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred))  # Decision Tree Accuracy 출력
print("Decision Tree Confusion Matrix: ", confusion_matrix(y_test, y_pred))  # Decision Tree Confusion Matrix 출력

Decision Tree Accuracy: 0.9739884393063584
Decision Tree Confusion Matrix:  [[ 76   6   1   0]
 [  1  10   0   0]
 [  0   0 235   0]
 [  1   0   0  16]]


In [36]:
# RandomForest
model = RandomForestClassifier(n_estimators=100, random_state=42)  #RandomForestClassifier 모델 생성, 100개의 DT를 사용해 학습 진행
model.fit(X_train, y_train)  # X_train 데이터의 패턴으로 모델을 학습
y_pred = model.predict(X_test)  # 학습된 모델로 X_test에 대해 예측

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred))  # Random Forest Accuracy 출력
print("Random Forest Confusion Matrix:", confusion_matrix(y_test, y_pred))  # Random Forest Confusion Matrix 출력

Random Forest Accuracy: 0.976878612716763
Random Forest Confusion Matrix: [[ 76   7   0   0]
 [  0  11   0   0]
 [  0   0 235   0]
 [  1   0   0  16]]


In [38]:
# SVC
model = SVC(kernel="linear", random_state=42)  # SVC 모델 생성, 선형 커널 사용
model.fit(X_train, y_train)  # X_train 데이터의 패턴으로 모델을 학습
y_pred = model.predict(X_test)  # 학습된 모델로 X_test에 대해 예측

print("SVM Accuracy:", accuracy_score(y_test, y_pred))  # SVM Accuracy 출력
print("SVM Confusion Matrix:", confusion_matrix(y_test, y_pred))  # SVM Confusion Matrix 출력

SVM Accuracy: 0.6965317919075145
SVM Confusion Matrix: [[ 10   0  73   0]
 [  0   0  11   0]
 [  4   0 231   0]
 [  7   0  10   0]]


In [40]:
# LogisticRegression
model = LogisticRegression(max_iter=200, random_state=42)  # LogisticRegression 모델 생성,  최대 반복 횟수 200 설정
model.fit(X_train, y_train)  # X_train 데이터의 패턴으로 모델을 학습
y_pred = model.predict(X_test)  # 학습된 모델로 X_test에 대해 예측

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred))  # Logistic Regression Accuracy 출력
print("Logistic Regression Confusion Matrix:", confusion_matrix(y_test, y_pred))  # Logistic Regression Confusion Matrix 출력

Logistic Regression Accuracy: 0.661849710982659
Logistic Regression Confusion Matrix: [[ 12   0  68   3]
 [  2   0   9   0]
 [ 17   0 217   1]
 [ 12   0   5   0]]


In [42]:
# KNN
knn = KNeighborsClassifier(n_neighbors=3)  # KNN 모델 생성, 예측을 위한 이웃의 수 설정
knn.fit(X_train, y_train)  # X_train 데이터의 패턴으로 Knn을 학습
y_pred = knn.predict(X_test)  # 학습된 모델로 X_test에 대해 예측

print("K-Nearest Neighbors Accuracy:", accuracy_score(y_test, y_pred))  # K-Nearest Neighbors Accuracy 출력
print("K-Nearest Neighbors Confusion Matrix:", confusion_matrix(y_test, y_pred))  # K-Nearest Neighbors Confusion Matrix 출력

K-Nearest Neighbors Accuracy: 0.9190751445086706
K-Nearest Neighbors Confusion Matrix: [[ 73   4   5   1]
 [  4   7   0   0]
 [ 12   0 223   0]
 [  2   0   0  15]]
